### PR TITLE
Removing a blank fungible entry

### PR DESCRIPTION
**Pull request by slacAWallace**
## Description

Taxon change

## Motivation and Context
There was a blank fungible, it doesn't make sense to keep it.

### CODE REVIEW

**Review by tangkong — APPROVED** [review]
Sensible.  Do we eventually want a fungible for spectrometers?

**Comment by janeliu-slac** [comment]
Ah, I had missed the blank fungible entry. Most of the tests are failing due to one unit test for displaying the current version of the naming tool. It should be fixed once I get the argparse module working.

**Review by ZLLentz — APPROVED** [review]
Seems to have come from the blank rows in https://docs.google.com/spreadsheets/d/1u5EfR9FIvwyTieWiMkCRqpBfHj-_xm3AygjFlxxWgDc/edit?gid=0#gid=0

When extracting that sheet into a json dict, the blank line after DP3 got inserted, and then the later blank lines replaced the dictionary entries. The final blank entry is the "Spectrometer" thing here.

**Comment by janeliu-slac** [comment]
Looks like an issue extracting data from the spreadsheet into the JSON files. Will re-do this for all the taxons and check they're correctly read into the json dictionaries.

**Pull request merged**
